[package]
name = "pirouette"
description = "A log/backup rotation tool."
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
flate2 = "1.1.0"
serde = { version = "1.0.218", features = ["derive"] }
tar = "0.4.44"
toml = "0.8.20"
uu_cp = "0.0.30"
