
[source]
path = "./sample/source.txt"

[target]
path = "./sample/target"

[retention]
days = 7
weeks = 4

[options]
output_format = "tarball"
# src: deep copy? shallow? latest file only?
# glob include/exclude patterns would be nice at some point too.
# custom-defined retention periods would be nice
