name: Pirouette CI

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      
      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      
      - name: cargo test
        run: cargo test --all-features

      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings

  publish_crate:
    needs: build_and_test
    name: Push crate to crates.io
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check cargo version matches git tag
        run: |
          cargo install toml-cli
          test "v$(toml get -r Cargo.toml package.version)" = "${{ github.ref_name }}"

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_CRATESIO_TOKEN }}

  publish_container:
    needs: build_and_test
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ vars.DOCKER_REPO }}
