name: Publish cargo crate

on:
  workflow_dispatch:

  release:
    types: [published]

  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push crate to crates.io
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_CRATESIO_TOKEN }}
